fix key for dynamodb_local
baopham/laravel-dynamodb pull request #272
Opened 2023-07-09 07:26 UTC by crhg

The recent 2.0.0 release of dynamodb_local no longer allows non-alphanumeric characters in the credential key as an incompatible change.
`config/dynamodb.php` use the string "dynamodb_local" as the key, but in dynamodb_local 2.0.0, using this string results in an error. This PR solves this problem.

https://hub.docker.com/r/amazon/dynamodb-local
> DynamoDB local version 2.0.0 and greater AWS_ACCESS_KEY_ID can contain the only letters (A–Z, a–z) and numbers (0–9).

2023-07-09 07:26 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/baopham/laravel-dynamodb/inspections/1f6f617e-9bfb-4520-b1a9-b271beba0c6d) was created.

2023-07-09 07:35 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/baopham/laravel-dynamodb/inspections/1f6f617e-9bfb-4520-b1a9-b271beba0c6d) completed: **No new issues**

2023-07-09 12:12 UTC, nelson6e65 requested changes
Thanks, @crhg! Only 1 missing place for this change:
https://github.com/baopham/laravel-dynamodb/blob/4e35d27b2c5db0f42220b5c6f0e20d83f936909c/tests/DynamoDbTestCase.php#L37

Update that line too and we are ready to go!

2023-07-10 00:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/baopham/laravel-dynamodb/inspections/9b2fd6a3-3e79-4800-8016-768b62cb1b74) was created.

2023-07-10 00:50 UTC, crhg commented
Thanks for your feedback.
The same fix was made for key in DynamoDbTestCase.php.

2023-07-10 00:51 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/baopham/laravel-dynamodb/inspections/9b2fd6a3-3e79-4800-8016-768b62cb1b74) completed: **No new issues**

2023-07-10 02:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/baopham/laravel-dynamodb/inspections/38001c0a-04d4-424c-92b8-aee31997dd1d) was created.

2023-07-10 03:02 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/baopham/laravel-dynamodb/inspections/38001c0a-04d4-424c-92b8-aee31997dd1d) completed: **No new issues**

2023-07-10 03:14 UTC, crhg commented
I changed the credential key setting in `DynamoDbTestCase.php`, and the name of the database file that dynamodb-local accesses must be `<credential key>_<region>.db`, so `setUpDatabase()` function also needed to modify the name of the destination file to be copied.

Should I also modify the filenames of `dynamodb_local_init.db` and  `dynamodb_local_schema.js`?

2023-07-10 05:06 UTC, nelson6e65 commented
I'm actually rewriting the tests to use Docker instead. I'll check this. Thanks.

2023-07-10 05:36 UTC, nelson6e65 approved these changes

2023-07-10 05:36 UTC, merged

2023-07-10 05:41 UTC, nelson6e65 commented
🚀 [v6.4.0](https://github.com/baopham/laravel-dynamodb/releases/tag/6.4.0)